POST http://localhost:8000/addaccess
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiIyIiwiZG9vcklEIjoiMyIsInN0YXJ0RGF0ZSI6IjA2LjIyLjIxIiwiZW5kRGF0ZSI6IjA2LjI2LjIxIiwiaWF0IjoxNjI0NDg0MTU0LCJleHAiOjE2MjQ0ODc3NTR9.RxEZzOMAmM61RLoUVovHyRuYJ2jyAvDocFcp-Srq9u4"
}

###

GET http://localhost:8000/getAllDoorsFromUser?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiIyIiwiZG9vcklEIjoiMyIsInN0YXJ0RGF0ZSI6IjA2LjIyLjIxIiwiZW5kRGF0ZSI6IjA2LjI2LjIxIiwiaWF0IjoxNjI0NDg0MTU0LCJleHAiOjE2MjQ0ODc3NTR9.RxEZzOMAmM61RLoUVovHyRuYJ2jyAvDocFcp-Srq9u4

###


###

### False
GET http://localhost:8000/checkaccess?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiIyIiwiZG9vcklEIjoiMyIsInN0YXJ0RGF0ZSI6IjA2LjIyLjIxIiwiZW5kRGF0ZSI6IjA2LjI2LjIxIiwiaWF0IjoxNjI0NDg0MTU0LCJleHAiOjE2MjQ0ODc3NTR9.RxEZzOMAmM61RLoUVovHyRuYJ2jyAvDocFcp-Srq9u4


###

POST http://localhost:8000/addUser
Content-Type: application/json

{
  "user": {
    "userID": 3,
    "firstname": "Chrissy",
    "lastname": "Raffeiner",
    "email": "Chrissy@gmail.com",
    "role": "user"
  }
}


###


DELETE http://localhost:8000/deleteUser
Content-Type: application/json

{
  "userID": 3
}


###

DELETE http://localhost:8000/deleteUser?userID=3

