POST http://localhost:8000/addaccess
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiIyNDEiLCJkb29ySUQiOlsiMjgiLCIyOCJdLCJzdGFydERhdGUiOlsiM2Q_dXNlcklEPTI0MSIsIjM0Il0sImVuZERhdGUiOlsiMjIiLCIyMiJdLCJpYXQiOjE2MjM5MTEwMzgsImV4cCI6MTYyMzkxNDYzOH0.goTDtsQRFKIOYJc9lJOqN2Ej_kZttCUgfm35KXSdusM"
}

###

GET http://localhost:8000/getAllDoorsFromUser
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiIxIiwiZG9vcklEIjoiMyIsInN0YXJ0RGF0ZSI6IlRodSBKdW4gMTAgMjAyMSAwMDowMDowMCBHTVQgMDIwMCAoTWl0dGVsZXVyb3DDpGlzY2hlIFNvbW1lcnplaXQpIiwiZW5kRGF0ZSI6IlRodSBKdW4gMjQgMjAyMSAwMDowMDowMCBHTVQgMDIwMCAoTWl0dGVsZXVyb3DDpGlzY2hlIFNvbW1lcnplaXQpIiwiaWF0IjoxNjI0NDU0OTk4LCJleHAiOjE2MjQ0NTg1OTh9.qsyovPqcluQ2M6MHBnHlPzzLTiyN0LaAeYDG5ROLwn4"
}

###


#True
GET http://localhost:8000/checkaccess
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiIyNDEiLCJkb29ySUQiOlsiMjgiLCIyOCJdLCJzdGFydERhdGUiOlsiM2Q_dXNlcklEPTI0MSIsIjM0Il0sImVuZERhdGUiOlsiMjIiLCIyMiJdLCJpYXQiOjE2MjM5MTEwMzgsImV4cCI6MTYyMzkxNDYzOH0.goTDtsQRFKIOYJc9lJOqN2Ej_kZttCUgfm35KXSdusM"
}


###


#False
GET http://localhost:8000/checkaccess
Content-Type: application/json

{
  "token": "eyJhbGJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiIyNDEiLCJkb29ySUQiOlsiMjgiLCIyOCJdLCJzdGFydERhdGUiOlsiM2Q_dXNlcklEPTI0MSIsIjM0Il0sImVuZERhdGUiOlsiMjIiLCIyMiJdLCJpYXQiOjE2MjM5MTEwMzgsImV4cCI6MTYyMzkxNDYzOH0.goTDtsQRFKIOYJc9lJOqN2Ej_kZttCUgfm35KXSdusM"
}


###

POST http://localhost:8000/addUser
Content-Type: application/json

{
  "user": {
    "userID": 3,
    "firstname": "Chrissy",
    "lastname": "Raffeiner",
    "email": "Chrissy@gmail.com",
    "role": "user"
  }
}
